---
- name: Generate and Install Configuration File
  hosts: "{{ services }}"
  roles:
    - Juniper.junos
    - build_config
    - security
    - telegram
  connection: local
  gather_facts: no

  vars:
    config_file: "{{ config_assemble }}/all.conf"
  
  tasks:
    - name: assemble config fragments
      assemble:
        src: "{{ config_assemble_build }}"
        dest: "{{ config_file }}"
    
    - name: install config onto device
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        src: "{{ config_file }}"
        load: merge
        confirmed: "{{ confirm_time }}"
        diff: yes
        ignore_warning: yes
        comment:  "commit confirmed {{ confirm_time }}"
      notify: confirm commit
    - name: Send notify to Telegram
        community.general.telegram:
        token: '6060974585:AAFM95tyQjzo52CMHZQknzTM9teHk0_2OuY'
        api_args:
          chat_id: -900228251
          parse_mode: "markdown"
          text: "[{{ services }}] Source IP Address {{ source_addresses }} has been blocked - Reason: {{ reason }}"
          disable_web_page_preview: True
          disable_notification: True
      
  handlers:
    - name: confirm commit
      juniper_junos_config:
        provider: "{{ connection_settings }}"
        commit: yes
        comment:  "confirming previous commit"
